server:
  port: 7777

video:
  location: videos/

image:
  location: images/

spring:
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl

  datasource:
    url: jdbc:mysql://localhost:3306/urunner_db?serverTimezone=UTC&useSSL=false
    username: khweb
    password: khWeb@123

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  security:
    oauth2:
      client:
        registration:

          google:
            clientId: 1060050007604-qkf4cdtom91ld9rt8230req72831rsah.apps.googleusercontent.com
            clientSecret: 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
            #              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

          github:
            clientId: d3c818f33bef13705f12
            clientSecret: 0e257a36c2e73c16bc66fd163c11cbfdd9633a89
            #            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user

          facebook:
            clientId: 1284375038693694
            clientSecret: 4457004f91cd26c28b1a9fb3cc127c82
            #              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile

          kakao:
            clientId: 569b009fc6904fb06e940ae715536c23
            clientSecret: BTO4VzAs7q4XnWh3v83cUs0XselrDFyI
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: "http://localhost:7777/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            clientName: Kakao

          naver:
            clientId: 4E16GfroEp1MlOrmLTHt
            clientSecret: aqGt8SdRPB
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: "http://localhost:7777/login/oauth2/code/naver"
            scope:
              - nickname
              - email
              - profile_image
            clientName: Naver

        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response

          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id


  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/oauth2/redirect
      -
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


